from .productosViews import ProductosListView
from .productosViews import ProductosDetailView
from .productosViews import ProductosDetailNameView
from .userDetailView import UserDetailView
from .userCreateView import UserCreateView
from .userListView import UserListView
from .roleView import RoleListView
from .roleView import RoleDetailView
from .categoryView import CategoryListView
from .categoryView import CategoryDetailView
from .verifyTokenView import VerifyTokenView