from .productosViews import ProductosListView
from .productosViews import ProductosDetailView
from .userView import UserListView
from .userView import UserDetailView
from .roleView import RoleListView
from .roleView import RoleDetailView
from .categoryView import CategoryListView
from .categoryView import CategoryDetailView
from .verifyTokenView import VerifyTokenView